#!/usr/bin/env bash

IFS='.' read -r type name ignore <<< "${HOSTNAME}"
component="$(echo "${type}_${name}" | awk '{print toupper($0)}')"
pass="${component}_PASS"
user="${component}_USER"
unset type name ignore component

PGPASSWORD="${!pass}" /data/bin/pg_dumpall -c -U ${!user}
