#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# verify postgresql is stopped
if ! `pgrep postgres`.empty?
  puts "PostgreSQL is still running"
  exit 1
end

execute "send diff data to new member" do
  command "rsync --delete -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' --exclude=/data/var/db/postgresql/postgresql.conf --exclude=/data/var/db/postgresql/pg_hba.conf -a /data/var/db/postgresql/. #{payload[:member][:local_ip]}:/data/var/db/postgresql/"
end
