#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Ensure the database is stopped before running import/export
service 'db' do
  action :disable
  init :runit
  only_if { File.exist?('/etc/service/db/run') }
  not_if { !Dir.exist?('/etc/service/db') }
end

begin
  execute "kill db" do
    command "pg_ctl stop -w -D /data/var/db/postgresql -m f"
    user 'gonano'
    only_if { File.exist?('/data/var/db/postgresql/postmaster.pid') }
  end
rescue
end

directory '/etc/service/db' do
  action :delete
  not_if { !Dir.exist?('/etc/service/db') }
end

# # Import service (and start)
directory '/etc/service/ssh' do
  recursive true
end

directory '/etc/service/ssh/log' do
  recursive true
end

template '/etc/service/ssh/log/run' do
  mode 0755
  source 'log-run.erb'
  variables ({ svc: "ssh" })
end

template '/etc/service/ssh/run' do
  mode 0755
  source 'run-root.erb'
  variables ({ exec: "/opt/gonano/sbin/sshd -D -e 2>&1" })
end

service 'ssh' do
  action :enable
  init :runit
  only_if { File.exist?('/etc/service/ssh/run') }
end

ensure_socket 'ssh' do
  port '22'
  action :listening
end
