#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'
require 'json'

include Hooky::Postgresql

config = converge( CONFIG_DEFAULTS, payload[:config] )

users = config[:users]

plan = {
  redundant: true,
  horizontal: false,
  user: 'nanobox',
  users: users,
  ips: [:default],
  port: 5342,
  behaviors: [:migratable, :backupable]
}

puts JSON.pretty_generate(plan)
