#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

include Hooky::Postgresql

# Setup
boxfile = converge( BOXFILE_DEFAULTS, payload[:boxfile] )

template '/data/etc/yoke.ini' do
  mode 0644
  owner 'gonano'
  group 'gonano'
end
