#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

payload[:members].each do |member|

  if ["primary", "secondary", "default"].include? member[:role]

    execute "send bulk data to new member" do
      command "tar -cf - --exclude=/data/var/db/postgresql/postgresql.conf -exclude=/data/var/db/postgresql/pg_hba.conf /data/var/db/postgresql | ssh -o StrictHostKeyChecking=no #{member[:local_ip]} tar -xpf -"
    end

  end
end
