#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

service 'db' do
  action :disable
  init :runit
  only_if { File.exist?('/etc/service/db/run') }
  not_if { !Dir.exist?('/etc/service/db') }
end

begin
  execute "kill db" do
    command "pg_ctl stop -w -D /data/var/db/postgresql -m f"
  end
rescue
end

directory '/etc/service/db' do
  action :delete
  not_if { !Dir.exist?('/etc/service/db') }
end

service 'ssh' do
  action :disable
  init :runit
  only_if { File.exist?('/etc/service/ssh/run') }
  not_if { !Dir.exist?('/etc/service/ssh') }
end

directory '/etc/service/ssh' do
  action :delete
  not_if { !Dir.exist?('/etc/service/ssh') }
end
